### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by maelle** [timtrice/rrricanesdata#4]
:wave: @timtrice! Would it make sense to get rid of the unused Docker "service"? Cf https://github.com/ropensci/rrricanesdata/settings/installations thanks!

**Comment by timtrice** [comment]
Hi @maelle ,

The  Docker service is used to rebuild images automatically when the master branch is updated. I do see the services are being deprecated so I'll have to look into that. Is that the reason for your question?

**Comment by maelle** [comment]
Yes I've listed all broken/inactive hooks and services over repos and found that one hence my notification. :-)

**Comment by timtrice** [comment]
Thank you for bringing it to my attention! I'll look for a resolution soon as I get a chance.

**Comment by maelle** [comment]
Maybe when clicking on the service it'll have an easy update option, fingers crossed.

**Comment by timtrice** [comment]
@maelle, yes, I have the green check mark now and the test seems to be working after I added the develop branch. So, I'm assuming this is fixed now,  as well?

**Comment by maelle** [comment]
Cool, yes!
